In [19]:
l=[]
for i in range (2000,3201):
    if ((i % 7)==0 and (i % 5 ) != 0 ):
        l.append(i)
l

[2002,
 2009,
 2016,
 2023,
 2037,
 2044,
 2051,
 2058,
 2072,
 2079,
 2086,
 2093,
 2107,
 2114,
 2121,
 2128,
 2142,
 2149,
 2156,
 2163,
 2177,
 2184,
 2191,
 2198,
 2212,
 2219,
 2226,
 2233,
 2247,
 2254,
 2261,
 2268,
 2282,
 2289,
 2296,
 2303,
 2317,
 2324,
 2331,
 2338,
 2352,
 2359,
 2366,
 2373,
 2387,
 2394,
 2401,
 2408,
 2422,
 2429,
 2436,
 2443,
 2457,
 2464,
 2471,
 2478,
 2492,
 2499,
 2506,
 2513,
 2527,
 2534,
 2541,
 2548,
 2562,
 2569,
 2576,
 2583,
 2597,
 2604,
 2611,
 2618,
 2632,
 2639,
 2646,
 2653,
 2667,
 2674,
 2681,
 2688,
 2702,
 2709,
 2716,
 2723,
 2737,
 2744,
 2751,
 2758,
 2772,
 2779,
 2786,
 2793,
 2807,
 2814,
 2821,
 2828,
 2842,
 2849,
 2856,
 2863,
 2877,
 2884,
 2891,
 2898,
 2912,
 2919,
 2926,
 2933,
 2947,
 2954,
 2961,
 2968,
 2982,
 2989,
 2996,
 3003,
 3017,
 3024,
 3031,
 3038,
 3052,
 3059,
 3066,
 3073,
 3087,
 3094,
 3101,
 3108,
 3122,
 3129,
 3136,
 3143,
 3157,
 3164,
 3171,
 3178,
 3192,
 3199]

In [18]:
x=int (input("give a number"))
z=1
for i in range (x,0,-1):
    z=z*i
z

give a number10


3628800

In [17]:
dict={}
n=int (input("give a number"))
for i in range (1,n+1):
    dict[i]=i*i
dict
    

give a number8


{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64}

In [16]:
ch=input("give a word ")
ch1=""
index=100
while index > len(ch)-1:
    index=int(input('give a number '))
for i in range (0,index):
    ch1=ch1+ch[i]
for i in range (index+1,len(ch)):
    ch1=ch1+ch[i]
ch1 




give a word hayderrrrrr
give a number 5


'hayderrrrr'

In [48]:
import numpy as np 
a=np.random.randint(1,100, size=[3,3])
print(a)
a.tolist()


[[33  5 10]
 [ 6 33 73]
 [21 15 55]]


[[33, 5, 10], [6, 33, 73], [21, 15, 55]]

In [31]:
import numpy as np
a=np.random.randint(1,100, size=[3,3])
print(a)
np.cov(a).tolist()



[[23 92 51]
 [ 9  4 81]
 [43 67 27]]


[[1204.3333333333333, -247.66666666666669, 474.6666666666667],
 [-247.66666666666669, 1856.3333333333335, -725.3333333333334],
 [474.6666666666667, -725.3333333333334, 405.3333333333333]]

In [47]:
import math
c=50
h=30
d=input('give the numbers')
d=d+','
x=0
ch1=''
for i in range(0,len(d)):
    if (d[i]==','):
        a=int(d[x:i])
        x=i+1
        q=math.sqrt((2*c*a)/h)
        q1=int(q)
        ch=str(q1)
        ch1=ch1+','+ch
print(ch1[1:])
        

give the numbers100,150,180
18,22,24
